/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ChamCongDAO;
import DAO.NhanVienDAO;
import DAO.TrangChuDAO;
import Model.ChamCongModel;
import Model.NhanVienModel;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ChamCongFrame extends javax.swing.JFrame {

    private static NhanVienModel currentUser;
    private DefaultTableModel TableCC;
    ArrayList<NhanVienModel> DSNV = new ArrayList<NhanVienModel>();

    public ChamCongFrame() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        TableCC = (DefaultTableModel) ChamCongJTable.getModel();
        DSNV = new ArrayList<>();
        LoadDanhSachCC();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String formattedDate = LocalDate.now().format(formatter);
        NgayHienTai.setText(formattedDate);

    }

    public void LoadDanhSachCC() throws SQLException {
        DefaultTableModel tableKM = (DefaultTableModel) ChamCongJTable.getModel();
        DSNV = NhanVienDAO.getDSNhanVien();
        tableKM.setRowCount(0);
        for (NhanVienModel km : DSNV) {
            tableKM.addRow(new Object[]{km.getMaNV(), km.getTenNV(), km.getNgaySinh(), km.getCCCD(), km.getGioiTinh(), km.getDiaChi(), km.getLoaiNV()});
        }
    }

    public void Display() throws SQLException {
        DSNV = NhanVienDAO.getDSNhanVien();
        NhanVienModel nv = new NhanVienModel();
        ArrayList<ChamCongModel> DSCC = new ArrayList<ChamCongModel>();
        int[] selectedrow = ChamCongJTable.getSelectedRows();
        try {
            Integer MaNV = Integer.parseInt(ChamCongJTable.getValueAt(selectedrow[0], 0).toString());
            NhapMaNhanVienTextField.setText(String.valueOf(MaNV));
            String LoaiNV = (String) ChamCongJTable.getValueAt(selectedrow[0], 6);
            ChucVuTextField.setText(LoaiNV);
            DSCC = ChamCongDAO.showMACC(MaNV);
            for (ChamCongModel ccm : DSCC) {
                MaChamCongTextField.setText(String.valueOf(ccm.getmaCC()));
                SoGioChamCongTextField.setText(String.valueOf(ccm.getSGLT()));
                SoNgayDiLamTextField.setText(String.valueOf(ccm.getSNDL()));
            }
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    public void TraCuuNV() {
        DefaultTableModel tblNV_Model = (DefaultTableModel) ChamCongJTable.getModel();
        String option = String.valueOf(TimKiemTheoJComboBox.getSelectedItem());
        String input = NhapThongTinField.getText().toLowerCase();
        tblNV_Model.setRowCount(0);
        ArrayList<NhanVienModel> DS_NV = new ArrayList<NhanVienModel>();
        DS_NV = NhanVienDAO.TimNV(option, input);
        for (NhanVienModel temp : DS_NV) {
            tblNV_Model.addRow(new Object[]{temp.getMaNV(),
                temp.getTenNV(), temp.getNgaySinh(), temp.getCCCD(), temp.getGioiTinh(), temp.getDiaChi(),
                temp.getLoaiNV()});
        }

        if (DS_NV.size() <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Thông tin không tồn tại. Vui lòng thử lại!",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        KhachHangLb = new javax.swing.JLabel();
        NhanVienLb = new javax.swing.JLabel();
        HopDongLb = new javax.swing.JLabel();
        KhuyenMaiLb = new javax.swing.JLabel();
        TrangBiLb = new javax.swing.JLabel();
        HoaDonLb = new javax.swing.JLabel();
        ChamCongLb = new javax.swing.JLabel();
        DangXuatLb = new javax.swing.JLabel();
        luongLb = new javax.swing.JLabel();
        phongLb = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ChamCongNgay = new javax.swing.JLabel();
        TimKiemTheoJComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NhapThongTinField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DangXuatButton = new javax.swing.JButton();
        ThucHienChamCongButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ChamCongJTable = new javax.swing.JTable();
        SoGioChamCongTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NhapMaNhanVienTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ChucVuTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        MaChamCongTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        SoNgayDiLamTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NgayHienTai = new javax.swing.JLabel();
        NhapSoGioLamThem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuPanel1.setBackground(new java.awt.Color(24, 24, 68));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(220, 220, 46));
        jLabel11.setText("BRIGHT STAR");

        KhachHangLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        KhachHangLb.setForeground(new java.awt.Color(255, 255, 255));
        KhachHangLb.setText("Khách hàng");
        KhachHangLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KhachHangLbMouseClicked(evt);
            }
        });

        NhanVienLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        NhanVienLb.setForeground(new java.awt.Color(255, 255, 255));
        NhanVienLb.setText("Nhân viên");
        NhanVienLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhanVienLbMouseClicked(evt);
            }
        });

        HopDongLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        HopDongLb.setForeground(new java.awt.Color(255, 255, 255));
        HopDongLb.setText("Hợp đồng");

        KhuyenMaiLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        KhuyenMaiLb.setForeground(new java.awt.Color(255, 255, 255));
        KhuyenMaiLb.setText("Khuyến mãi");

        TrangBiLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        TrangBiLb.setForeground(new java.awt.Color(255, 255, 255));
        TrangBiLb.setText("Trang bị");

        HoaDonLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        HoaDonLb.setForeground(new java.awt.Color(255, 255, 255));
        HoaDonLb.setText("Hoá đơn");

        ChamCongLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ChamCongLb.setForeground(new java.awt.Color(255, 255, 255));
        ChamCongLb.setText("Chấm công");
        ChamCongLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChamCongLbMouseClicked(evt);
            }
        });

        DangXuatLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        DangXuatLb.setForeground(new java.awt.Color(255, 255, 255));
        DangXuatLb.setText("Đăng xuất");
        DangXuatLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DangXuatLbMouseClicked(evt);
            }
        });

        luongLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        luongLb.setForeground(new java.awt.Color(255, 255, 255));
        luongLb.setText("Lương");
        luongLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                luongLbMouseClicked(evt);
            }
        });

        phongLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        phongLb.setForeground(new java.awt.Color(255, 255, 255));
        phongLb.setText("Phòng");

        javax.swing.GroupLayout MenuPanel1Layout = new javax.swing.GroupLayout(MenuPanel1);
        MenuPanel1.setLayout(MenuPanel1Layout);
        MenuPanel1Layout.setHorizontalGroup(
            MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanel1Layout.createSequentialGroup()
                .addGroup(MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(MenuPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(KhachHangLb))
                    .addGroup(MenuPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(NhanVienLb))
                    .addGroup(MenuPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(HopDongLb))
                    .addGroup(MenuPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(KhuyenMaiLb))
                    .addGroup(MenuPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(TrangBiLb))
                    .addGroup(MenuPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(HoaDonLb))
                    .addGroup(MenuPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(luongLb)
                            .addComponent(ChamCongLb)
                            .addComponent(DangXuatLb)
                            .addComponent(phongLb))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        MenuPanel1Layout.setVerticalGroup(
            MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(phongLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KhachHangLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NhanVienLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HopDongLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KhuyenMaiLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TrangBiLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HoaDonLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChamCongLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(luongLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(DangXuatLb)
                .addGap(32, 32, 32))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Chấm công ");

        ChamCongNgay.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ChamCongNgay.setText("Chấm công ngày :");

        TimKiemTheoJComboBox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TimKiemTheoJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã NV", "Tên NV", "Chức vụ" }));
        TimKiemTheoJComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TimKiemTheoJComboBoxItemStateChanged(evt);
            }
        });
        TimKiemTheoJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemTheoJComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Tìm kiếm theo");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Nhập thông tin ");

        NhapThongTinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhapThongTinFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Bảng chấm công");

        DangXuatButton.setBackground(new java.awt.Color(24, 24, 68));
        DangXuatButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DangXuatButton.setForeground(new java.awt.Color(255, 255, 255));
        DangXuatButton.setText("Đăng xuất ");
        DangXuatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangXuatButtonActionPerformed(evt);
            }
        });

        ThucHienChamCongButton.setBackground(new java.awt.Color(153, 153, 255));
        ThucHienChamCongButton.setText("Chấm công");
        ThucHienChamCongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThucHienChamCongButtonActionPerformed(evt);
            }
        });

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        ChamCongJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên NV", "Ngày Sinh", "CCCD", "Giới tính ", "Địa chỉ ", "Loại NV"
            }
        ));
        ChamCongJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChamCongJTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ChamCongJTable);

        SoGioChamCongTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoGioChamCongTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Số giờ chấm công trong tháng");

        NhapMaNhanVienTextField.setEditable(false);
        NhapMaNhanVienTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NhapMaNhanVienTextFieldKeyPressed(evt);
            }
        });

        jLabel6.setText("Mã Nhân Viên");

        ChucVuTextField.setEditable(false);
        ChucVuTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChucVuTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Chức vụ");

        MaChamCongTextField.setEditable(false);
        MaChamCongTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaChamCongTextFieldActionPerformed(evt);
            }
        });
        MaChamCongTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MaChamCongTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MaChamCongTextFieldKeyReleased(evt);
            }
        });

        jLabel8.setText("Mã chấm công");

        SoNgayDiLamTextField.setEditable(false);
        SoNgayDiLamTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoNgayDiLamTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Số ngày đi làm ");

        jButton1.setBackground(new java.awt.Color(24, 24, 68));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tra cứu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NhapSoGioLamThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhapSoGioLamThemActionPerformed(evt);
            }
        });

        jLabel10.setText("Số giờ chấm công ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NhapSoGioLamThem, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(NhapMaNhanVienTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChucVuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SoNgayDiLamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ThucHienChamCongButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(SoGioChamCongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(242, 242, 242))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel2)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(TimKiemTheoJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NhapThongTinField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ChamCongNgay)
                                .addGap(18, 18, 18)
                                .addComponent(NgayHienTai)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DangXuatButton)))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6))
                            .addComponent(MaChamCongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChamCongNgay)
                    .addComponent(DangXuatButton)
                    .addComponent(NgayHienTai))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NhapThongTinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimKiemTheoJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(MaChamCongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NhapMaNhanVienTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChucVuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoNgayDiLamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoGioChamCongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThucHienChamCongButton)
                    .addComponent(NhapSoGioLamThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 640, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NhapThongTinFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhapThongTinFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NhapThongTinFieldActionPerformed

    private void DangXuatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangXuatButtonActionPerformed
        dispose();
        DangNhapFrame.main(null);
    }//GEN-LAST:event_DangXuatButtonActionPerformed

    private void ThucHienChamCongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThucHienChamCongButtonActionPerformed
        LocalDate today = LocalDate.now();
        int CapNhapTheo = Integer.parseInt(NhapMaNhanVienTextField.getText());
        int SOGIOLAMTHEM = Integer.parseInt(NhapSoGioLamThem.getText());

        try {
            ChamCongModel cc = new ChamCongModel(SOGIOLAMTHEM);

            if (ChamCongDAO.ChamCong(CapNhapTheo, cc)) {
                Display();
                JOptionPane.showMessageDialog(rootPane,
                        "Chấm công thành công!", "Thông báo", JOptionPane.PLAIN_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(rootPane, "Chấm công không thành công. Vui lòng thử lại!",
                        "Thông báo", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Lỗi!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ThucHienChamCongButtonActionPerformed

    private void SoGioChamCongTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoGioChamCongTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoGioChamCongTextFieldActionPerformed

    private void ChucVuTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChucVuTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChucVuTextFieldActionPerformed

    private void MaChamCongTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaChamCongTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaChamCongTextFieldActionPerformed

    private void SoNgayDiLamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoNgayDiLamTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoNgayDiLamTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String input = NhapThongTinField.getText();
            if (input.equals("")) {
                LoadDanhSachCC();
            } else {
                TraCuuNV();
            }
        } catch (SQLException ex) {
            Logger.getLogger(ChamCongFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TimKiemTheoJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemTheoJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimKiemTheoJComboBoxActionPerformed

    private void TimKiemTheoJComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TimKiemTheoJComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TimKiemTheoJComboBoxItemStateChanged

    private void ChamCongJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChamCongJTableMouseClicked
        try {
            Display();
        } catch (SQLException ex) {
            Logger.getLogger(ChamCongFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ChamCongJTableMouseClicked

    private void MaChamCongTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MaChamCongTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_MaChamCongTextFieldKeyReleased

    private void MaChamCongTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MaChamCongTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaChamCongTextFieldKeyPressed

    private void NhapMaNhanVienTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NhapMaNhanVienTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //ShowMaCC();
            //NgayHienTai.setText(String.valueOf(java.time.LocalDate.now()));
        }
    }//GEN-LAST:event_NhapMaNhanVienTextFieldKeyPressed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        try {
            Display();
        } catch (SQLException ex) {
            Logger.getLogger(ChamCongFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void NhapSoGioLamThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhapSoGioLamThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NhapSoGioLamThemActionPerformed

    private void KhachHangLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhachHangLbMouseClicked
        dispose();
        KhachHangFrame.main(currentUser);
    }//GEN-LAST:event_KhachHangLbMouseClicked

    private void NhanVienLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhanVienLbMouseClicked
        //        System.out.println(currentUser.toString());
        if (TrangChuDAO.KTLoaiNV(currentUser.getMaNV()) == 1) {
            dispose();
            NhanVienFrame.main(currentUser);
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập vào chức năng này", "Thông báo", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_NhanVienLbMouseClicked

    private void ChamCongLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChamCongLbMouseClicked
        if (TrangChuDAO.KTLoaiNV(currentUser.getMaNV()) == 1) {
            dispose();
            ChamCongFrame.main(currentUser);
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập vào chức năng này", "Thông báo", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_ChamCongLbMouseClicked

    private void DangXuatLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuatLbMouseClicked
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất không?", "Đăng xuất", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            dispose();
            DangNhapFrame.main(null);
        }
    }//GEN-LAST:event_DangXuatLbMouseClicked

    private void luongLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_luongLbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_luongLbMouseClicked

    private static NhanVienModel user;

    public static void main(NhanVienModel args) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChamCongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChamCongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChamCongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChamCongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        user = args;

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ChamCongFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ChamCongFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ChamCongJTable;
    private javax.swing.JLabel ChamCongLb;
    private javax.swing.JLabel ChamCongNgay;
    private javax.swing.JTextField ChucVuTextField;
    private javax.swing.JButton DangXuatButton;
    private javax.swing.JLabel DangXuatLb;
    private javax.swing.JLabel HoaDonLb;
    private javax.swing.JLabel HopDongLb;
    private javax.swing.JLabel KhachHangLb;
    private javax.swing.JLabel KhuyenMaiLb;
    private javax.swing.JTextField MaChamCongTextField;
    private javax.swing.JPanel MenuPanel1;
    private javax.swing.JLabel NgayHienTai;
    private javax.swing.JLabel NhanVienLb;
    private javax.swing.JTextField NhapMaNhanVienTextField;
    private javax.swing.JTextField NhapSoGioLamThem;
    private javax.swing.JTextField NhapThongTinField;
    private javax.swing.JTextField SoGioChamCongTextField;
    private javax.swing.JTextField SoNgayDiLamTextField;
    private javax.swing.JButton ThucHienChamCongButton;
    private javax.swing.JComboBox<String> TimKiemTheoJComboBox;
    private javax.swing.JLabel TrangBiLb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel luongLb;
    private javax.swing.JLabel phongLb;
    // End of variables declaration//GEN-END:variables
}
