/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.KhuyenMaiDAO;
import DAO.TrangChuDAO;
import Model.KhuyenMaiModel;
import Model.NhanVienModel;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class KhuyenMaiFrame extends javax.swing.JFrame {

    /**
     * Creates new form KhuyenMaiFrame
     */
    ArrayList<KhuyenMaiModel> DSKM ;
    int maKM;
    private static NhanVienModel currentUser;
    int current = 0;
    
    private DefaultTableModel TableKM = new DefaultTableModel(){
        public boolean isCellEdittable (int row, int column) {
            return false;
        }
    };
    
    public KhuyenMaiFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        

        khoiTaoBang();
        inDanhSach();
    }
    
    
    public void khoiTaoBang() {
        TableKM = new DefaultTableModel();
        
        TableKM.addColumn("Mã KM");
        TableKM.addColumn("Tên KM");
        TableKM.addColumn("Mô tả KM");
        TableKM.addColumn("Ngày bắt đầu");
        TableKM.addColumn("Ngày kết thúc");
        TableKM.addColumn("Phần trăm KM");
        
        DanhSachKhuyenMaiJTable.setModel (TableKM);
    }
    
    public void inDanhSach() {
        ArrayList<KhuyenMaiModel> DSKM = KhuyenMaiDAO.getDSKhuyenMai();
        TableKM.setRowCount(0);
        for (KhuyenMaiModel kmm : DSKM)
        {
            TableKM.addRow(new Object[] {kmm.getMaKM(), kmm.getTenKM(), kmm.getMoTaKM(), kmm.getNgayBatDau(), kmm.getNgayKetThuc(), kmm.getPhanTramKM()*100 + "%" });
        }
    }
    
    public void TraCuuKM() {
        String luachon = (String) this.TimKiemJComboBox.getSelectedItem();
        String input = this.NhapThongTinJTextField.getText(). toLowerCase();
        TableKM.setRowCount(0);
        ArrayList<KhuyenMaiModel> DSKM = KhuyenMaiDAO.TimKM(luachon, input);
        
        for (KhuyenMaiModel kmm : DSKM)
        {
           TableKM.addRow(new Object[]{kmm.getMaKM(), kmm.getTenKM(), kmm.getMoTaKM(), kmm.getNgayBatDau(), kmm.getNgayKetThuc(), kmm.getPhanTramKM() });
        }
        
        if (DSKM.size() <= 0)
        {
            JOptionPane.showMessageDialog(rootPane, "Thông tin không tồn tại. Vui lòng thử lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        KhachHangLb = new javax.swing.JLabel();
        NhanVienLb = new javax.swing.JLabel();
        HopDongLb = new javax.swing.JLabel();
        KhuyenMaiLb = new javax.swing.JLabel();
        TrangBiLb = new javax.swing.JLabel();
        HoaDonLb = new javax.swing.JLabel();
        ChamCongLb = new javax.swing.JLabel();
        DangXuatLb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TimKiemJComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        NhapThongTinJTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DanhSachKhuyenMaiJTable = new javax.swing.JTable();
        TraCuuJButton = new javax.swing.JButton();
        ThemJButton = new javax.swing.JButton();
        XoaJButton = new javax.swing.JButton();
        SuaJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(24, 24, 68));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(220, 220, 46));
        jLabel4.setText("BRIGHT STAR");

        KhachHangLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        KhachHangLb.setForeground(new java.awt.Color(255, 255, 255));
        KhachHangLb.setText("Khách hàng");
        KhachHangLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KhachHangLbMouseClicked(evt);
            }
        });

        NhanVienLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        NhanVienLb.setForeground(new java.awt.Color(255, 255, 255));
        NhanVienLb.setText("Nhân viên");
        NhanVienLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhanVienLbMouseClicked(evt);
            }
        });

        HopDongLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        HopDongLb.setForeground(new java.awt.Color(255, 255, 255));
        HopDongLb.setText("Hợp đồng");

        KhuyenMaiLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        KhuyenMaiLb.setForeground(new java.awt.Color(255, 255, 255));
        KhuyenMaiLb.setText("Khuyến mãi");

        TrangBiLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        TrangBiLb.setForeground(new java.awt.Color(255, 255, 255));
        TrangBiLb.setText("Trang bị");

        HoaDonLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        HoaDonLb.setForeground(new java.awt.Color(255, 255, 255));
        HoaDonLb.setText("Hoá đơn");

        ChamCongLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ChamCongLb.setForeground(new java.awt.Color(255, 255, 255));
        ChamCongLb.setText("Chấm công");
        ChamCongLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChamCongLbMouseClicked(evt);
            }
        });

        DangXuatLb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        DangXuatLb.setForeground(new java.awt.Color(255, 255, 255));
        DangXuatLb.setText("Đăng xuất");
        DangXuatLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DangXuatLbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KhachHangLb)
                            .addComponent(NhanVienLb)
                            .addComponent(HopDongLb)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TrangBiLb)
                            .addComponent(KhuyenMaiLb)
                            .addComponent(HoaDonLb)
                            .addComponent(ChamCongLb))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DangXuatLb)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addComponent(KhachHangLb)
                .addGap(27, 27, 27)
                .addComponent(NhanVienLb)
                .addGap(28, 28, 28)
                .addComponent(HopDongLb)
                .addGap(30, 30, 30)
                .addComponent(KhuyenMaiLb)
                .addGap(28, 28, 28)
                .addComponent(TrangBiLb)
                .addGap(26, 26, 26)
                .addComponent(HoaDonLb)
                .addGap(28, 28, 28)
                .addComponent(ChamCongLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DangXuatLb)
                .addGap(30, 30, 30))
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tìm kiếm theo ");

        TimKiemJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã KM", "Tên KM", "Ngày Bắt Đầu", "Ngày Kết Thúc", " ", " " }));
        TimKiemJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemJComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nhập thông tin ");

        NhapThongTinJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhapThongTinJTextFieldActionPerformed(evt);
            }
        });

        DanhSachKhuyenMaiJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã KM", "Tên KM", "Mô tả KM", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Phần Trăm KM"
            }
        ));
        jScrollPane1.setViewportView(DanhSachKhuyenMaiJTable);

        TraCuuJButton.setBackground(new java.awt.Color(24, 24, 68));
        TraCuuJButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TraCuuJButton.setForeground(new java.awt.Color(255, 255, 255));
        TraCuuJButton.setText("TRA CỨU");
        TraCuuJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraCuuJButtonActionPerformed(evt);
            }
        });

        ThemJButton.setBackground(new java.awt.Color(24, 24, 68));
        ThemJButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ThemJButton.setForeground(new java.awt.Color(255, 255, 255));
        ThemJButton.setText("THÊM");
        ThemJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemJButtonActionPerformed(evt);
            }
        });

        XoaJButton.setBackground(new java.awt.Color(24, 24, 68));
        XoaJButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        XoaJButton.setForeground(new java.awt.Color(255, 255, 255));
        XoaJButton.setText("XÓA");
        XoaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaJButtonActionPerformed(evt);
            }
        });

        SuaJButton.setBackground(new java.awt.Color(24, 24, 68));
        SuaJButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        SuaJButton.setForeground(new java.awt.Color(255, 255, 255));
        SuaJButton.setText("SỬA");
        SuaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaJButtonActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(24, 24, 68));
        jLabel8.setText("KHUYẾN MÃI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TimKiemJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(138, 138, 138)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(58, 280, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NhapThongTinJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TraCuuJButton)
                                .addGap(62, 62, 62))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel8)
                        .addGap(40, 260, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ThemJButton)
                        .addGap(37, 37, 37)
                        .addComponent(XoaJButton)
                        .addGap(44, 44, 44)
                        .addComponent(SuaJButton)
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TimKiemJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NhapThongTinJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TraCuuJButton))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThemJButton)
                    .addComponent(XoaJButton)
                    .addComponent(SuaJButton))
                .addGap(18, 18, 18))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TimKiemJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimKiemJComboBoxActionPerformed

    private void NhapThongTinJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhapThongTinJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NhapThongTinJTextFieldActionPerformed

    private void TraCuuJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraCuuJButtonActionPerformed
        // TODO add your handling code here:
        String input = this.NhapThongTinJTextField.getText();
        if (input.equals("")) {
            inDanhSach();
        }
        else
        {    
            TraCuuKM();
    }//GEN-LAST:event_TraCuuJButtonActionPerformed
    }
    private void SuaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaJButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = this.DanhSachKhuyenMaiJTable.getSelectedRow() ;
        
        try {
            if (selectedIndex == -1) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn dữ liệu cần sửa!", "Thông báo",JOptionPane.ERROR_MESSAGE);
            } else if (this.DanhSachKhuyenMaiJTable.getRowCount () == 0) {
                JOptionPane.showMessageDialog(rootPane,"Dữ liệu trống!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                Object maKMObject = this.DanhSachKhuyenMaiJTable.getValueAt(selectedIndex, 0);
                int maKM = (Integer) maKMObject;
                dispose ();
                SuaKhuyenMaiFrame.main(currentUser, maKM);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SuaJButtonActionPerformed

    private void ThemJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemJButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        ThemKhuyenMaiFrame.main(currentUser);
    }//GEN-LAST:event_ThemJButtonActionPerformed

    private void XoaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaJButtonActionPerformed
        // TODO add your handling code here:
        int removeIndex = this.DanhSachKhuyenMaiJTable.getSelectedRow();
        try {
            if (removeIndex == -1) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn dữ liệu cần xóa!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else if (this.DanhSachKhuyenMaiJTable.getRowCount() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Dữ liệu trống!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                Object maKMObject = this.DanhSachKhuyenMaiJTable.getValueAt(removeIndex, 0);
                maKM = (Integer) maKMObject;
                int choice = JOptionPane.showConfirmDialog(rootPane,"Bạn có chắc chắn muốn xóa không ?", "Xác nhận xóa", JOptionPane.OK_CANCEL_OPTION);
                if (choice == JOptionPane.OK_OPTION) {
                    int row = KhuyenMaiDAO.XoaKM(maKM);
                    if (row > 0) {
                        JOptionPane.showMessageDialog(rootPane, "Xóa thành công!", "Thông báo", JOptionPane.PLAIN_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Xóa không thành công. Vui lòng thử lại!","Thông báo", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane,"Đã hủy xóa!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
                inDanhSach();
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Lỗi!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_XoaJButtonActionPerformed

    private void KhachHangLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhachHangLbMouseClicked
        if (TrangChuDAO.KTLoaiNV(currentUser.getMaNV()) == 1 || TrangChuDAO.KTLoaiNV(currentUser.getMaNV()) == 2) {
            dispose();
            KhachHangFrame.main(currentUser);
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập vào chức năng này", "Thông báo", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_KhachHangLbMouseClicked

    private void NhanVienLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhanVienLbMouseClicked
        System.out.println(currentUser.toString());
        if (TrangChuDAO.KTLoaiNV(currentUser.getMaNV()) == 1) {
            dispose();
            NhanVienFrame.main(currentUser);
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập vào chức năng này", "Thông báo", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_NhanVienLbMouseClicked

    private void ChamCongLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChamCongLbMouseClicked
        if (TrangChuDAO.KTLoaiNV(currentUser.getMaNV()) == 1) {
            dispose();
            ChamCongFrame.main(currentUser);
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập vào chức năng này", "Thông báo", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_ChamCongLbMouseClicked

    private void DangXuatLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuatLbMouseClicked
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất không?", "Đăng xuất", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            dispose();
            DangNhapFrame.main(null);
        }
    }//GEN-LAST:event_DangXuatLbMouseClicked
     
    private void KhuyenMaiLbMouseClicked(java.awt.event.MouseEvent evt) {                                        
       System.out.println(currentUser.toString());
        if (TrangChuDAO.KTLoaiNV(currentUser.getMaNV()) == 1) {
            dispose();
            KhuyenMaiFrame.main(currentUser);
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập vào chức năng này", "Thông báo", JOptionPane.PLAIN_MESSAGE);
        }
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(NhanVienModel args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhuyenMaiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhuyenMaiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhuyenMaiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhuyenMaiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        currentUser = args;
        currentUser.setMaNV(args.getMaNV());
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus". equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
                new KhuyenMaiFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChamCongLb;
    private javax.swing.JLabel DangXuatLb;
    private javax.swing.JTable DanhSachKhuyenMaiJTable;
    private javax.swing.JLabel HoaDonLb;
    private javax.swing.JLabel HopDongLb;
    private javax.swing.JLabel KhachHangLb;
    private javax.swing.JLabel KhuyenMaiLb;
    private javax.swing.JLabel NhanVienLb;
    private javax.swing.JTextField NhapThongTinJTextField;
    private javax.swing.JButton SuaJButton;
    private javax.swing.JButton ThemJButton;
    private javax.swing.JComboBox<String> TimKiemJComboBox;
    private javax.swing.JButton TraCuuJButton;
    private javax.swing.JLabel TrangBiLb;
    private javax.swing.JButton XoaJButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
