/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.LuongDAO;
import DAO.TrangChuDAO;
import Model.LuongModel;
import Model.NhanVienModel;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phuch
 */
public class LuongFrame extends javax.swing.JFrame {
    private static NhanVienModel currentUser;
    ArrayList<LuongModel> DS_Luong;
    private DefaultTableModel tblLuong_Model;
    private LuongDAO luongDAO;
    public LuongFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        DS_Luong = new ArrayList<>();
        DefaultTableModel DefaultTableModel;
        tblLuong_Model = (DefaultTableModel) this.LuongJTable.getModel();
        LoadDSLuong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TimKiemTheoJCombobox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        NhapThongTinJTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        LuongJTable = new javax.swing.JTable();
        TraCuuButton = new javax.swing.JButton();
        TinhLuongButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TenNVTextField = new javax.swing.JTextField();
        LuongTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MenuPanel17 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        KhachHangLb16 = new javax.swing.JLabel();
        NhanVienLb16 = new javax.swing.JLabel();
        HopDongLb16 = new javax.swing.JLabel();
        KhuyenMaiLb16 = new javax.swing.JLabel();
        TrangBiLb16 = new javax.swing.JLabel();
        HoaDonLb16 = new javax.swing.JLabel();
        ChamCongLb16 = new javax.swing.JLabel();
        DangXuatLb16 = new javax.swing.JLabel();
        phongLb16 = new javax.swing.JLabel();
        luongLb16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Lương");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Tìm kiếm theo ");

        TimKiemTheoJCombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TimKiemTheoJCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã NV", "Tên NV" }));
        TimKiemTheoJCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemTheoJComboboxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Nhập thông tin");

        NhapThongTinJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhapThongTinJTextFieldActionPerformed(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        LuongJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã CC", "Mã NV", "Tên NV", "Chức vụ", "Lương CB", "Số ngày đi làm ", "Số giờ làm thêm"
            }
        ));
        LuongJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LuongJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(LuongJTable);

        TraCuuButton.setBackground(new java.awt.Color(24, 24, 68));
        TraCuuButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TraCuuButton.setForeground(new java.awt.Color(255, 255, 255));
        TraCuuButton.setText("Tra Cứu");
        TraCuuButton.setPreferredSize(new java.awt.Dimension(76, 27));
        TraCuuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraCuuButtonActionPerformed(evt);
            }
        });

        TinhLuongButton.setBackground(new java.awt.Color(24, 24, 68));
        TinhLuongButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TinhLuongButton.setForeground(new java.awt.Color(255, 255, 255));
        TinhLuongButton.setText("Tính Lương");
        TinhLuongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinhLuongButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Lương tháng này của nhân viên ");

        TenNVTextField.setEditable(false);
        TenNVTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenNVTextFieldActionPerformed(evt);
            }
        });

        LuongTextField.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("VNĐ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LuongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(228, 228, 228)
                                .addComponent(TinhLuongButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TenNVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(TimKiemTheoJCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NhapThongTinJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(TraCuuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimKiemTheoJCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TraCuuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NhapThongTinJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TenNVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TinhLuongButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LuongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(64, 64, 64))
        );

        MenuPanel17.setBackground(new java.awt.Color(24, 24, 68));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(220, 220, 46));
        jLabel22.setText("BRIGHT STAR");

        KhachHangLb16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        KhachHangLb16.setForeground(new java.awt.Color(255, 255, 255));
        KhachHangLb16.setText("Khách hàng");
        KhachHangLb16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KhachHangLb16MouseClicked(evt);
            }
        });

        NhanVienLb16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        NhanVienLb16.setForeground(new java.awt.Color(255, 255, 255));
        NhanVienLb16.setText("Nhân viên");
        NhanVienLb16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhanVienLb16MouseClicked(evt);
            }
        });

        HopDongLb16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        HopDongLb16.setForeground(new java.awt.Color(255, 255, 255));
        HopDongLb16.setText("Hợp đồng");

        KhuyenMaiLb16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        KhuyenMaiLb16.setForeground(new java.awt.Color(255, 255, 255));
        KhuyenMaiLb16.setText("Khuyến mãi");

        TrangBiLb16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        TrangBiLb16.setForeground(new java.awt.Color(255, 255, 255));
        TrangBiLb16.setText("Trang bị");

        HoaDonLb16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        HoaDonLb16.setForeground(new java.awt.Color(255, 255, 255));
        HoaDonLb16.setText("Hoá đơn");

        ChamCongLb16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ChamCongLb16.setForeground(new java.awt.Color(255, 255, 255));
        ChamCongLb16.setText("Chấm công");
        ChamCongLb16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChamCongLb16MouseClicked(evt);
            }
        });

        DangXuatLb16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        DangXuatLb16.setForeground(new java.awt.Color(255, 255, 255));
        DangXuatLb16.setText("Đăng xuất");
        DangXuatLb16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DangXuatLb16MouseClicked(evt);
            }
        });

        phongLb16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        phongLb16.setForeground(new java.awt.Color(255, 255, 255));
        phongLb16.setText("Phòng");

        luongLb16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        luongLb16.setForeground(new java.awt.Color(255, 255, 255));
        luongLb16.setText("Lương");

        javax.swing.GroupLayout MenuPanel17Layout = new javax.swing.GroupLayout(MenuPanel17);
        MenuPanel17.setLayout(MenuPanel17Layout);
        MenuPanel17Layout.setHorizontalGroup(
            MenuPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanel17Layout.createSequentialGroup()
                .addGroup(MenuPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanel17Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22))
                    .addGroup(MenuPanel17Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(NhanVienLb16))
                    .addGroup(MenuPanel17Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(HopDongLb16))
                    .addGroup(MenuPanel17Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(KhuyenMaiLb16))
                    .addGroup(MenuPanel17Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(TrangBiLb16))
                    .addGroup(MenuPanel17Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(HoaDonLb16))
                    .addGroup(MenuPanel17Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(DangXuatLb16))
                    .addGroup(MenuPanel17Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(MenuPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phongLb16)
                            .addComponent(KhachHangLb16)))
                    .addGroup(MenuPanel17Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(MenuPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(luongLb16)
                            .addComponent(ChamCongLb16))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        MenuPanel17Layout.setVerticalGroup(
            MenuPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanel17Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(phongLb16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KhachHangLb16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NhanVienLb16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HopDongLb16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KhuyenMaiLb16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TrangBiLb16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HoaDonLb16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChamCongLb16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(luongLb16)
                .addGap(30, 30, 30)
                .addComponent(DangXuatLb16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NhapThongTinJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhapThongTinJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NhapThongTinJTextFieldActionPerformed

    private void TimKiemTheoJComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemTheoJComboboxActionPerformed
      
    }//GEN-LAST:event_TimKiemTheoJComboboxActionPerformed
    public void LoadDSLuong() {
        ArrayList<LuongModel> DS_Luong = new ArrayList<>();
        DS_Luong = LuongDAO.getDSLuong();
        DefaultTableModel tblHienThi = (DefaultTableModel) this.LuongJTable.getModel();
        tblHienThi.setRowCount(0);
        for (LuongModel luong : DS_Luong) {
            tblLuong_Model.addRow(new Object[]{
                luong.getMaCC(),
                luong.getMaNV(),
                luong.getTenNV(),
                luong.getLoaiNV(),
                luong.getLuongCB(),
                luong.getSNDL(),
                luong.getSGLT()
            });
        }
    }
    private void TraCuuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraCuuButtonActionPerformed
      String input = this.NhapThongTinJTextField.getText();
        if (input.equals(""))
            LoadDSLuong();
        else
            TraCuuLuong();
    }//GEN-LAST:event_TraCuuButtonActionPerformed

    private void TinhLuongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinhLuongButtonActionPerformed
            LuongDAO luongDAO = new LuongDAO();
        int chooseIndex = this.LuongJTable.getSelectedRow();
        DefaultTableModel tblLuong_Model = (DefaultTableModel) this.LuongJTable.getModel();
        try {
            if (chooseIndex == -1) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn nhân viên cần tính lương!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else if (this.LuongJTable.getRowCount() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Dữ liệu trống!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                int choice = JOptionPane.showOptionDialog(rootPane, "Bạn có muốn tính lương cho nhân viên?", "Tính lương", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
                if (choice == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(rootPane, "Lương của nhân viên đã được tính", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    String MaCC = (String) tblLuong_Model.getValueAt(chooseIndex, 0);
                    String MaNV = (String) tblLuong_Model.getValueAt(chooseIndex, 1);
                    String TenNV = (String) tblLuong_Model.getValueAt(chooseIndex, 2);
                    String LoaiNV = (String) tblLuong_Model.getValueAt(chooseIndex, 3);
                    Double LuongCB = (Double) tblLuong_Model.getValueAt(chooseIndex, 4);
                    int SoNgayDiLam = (int) tblLuong_Model.getValueAt(chooseIndex, 5);
                    int SoGioLamThem = (int) tblLuong_Model.getValueAt(chooseIndex, 6);
                    LuongModel luong = new LuongModel(MaNV, MaCC, TenNV, LoaiNV, LuongCB, SoNgayDiLam, SoGioLamThem);
                    this.TenNVTextField.setText(TenNV);
                    double luongNV = luongDAO.TinhLuong(luong);
                    NumberFormat numberFormat = NumberFormat.getCurrencyInstance();
                    String formattedNumber = numberFormat.format(luongNV);
                    this.LuongTextField.setText(formattedNumber);
                    LuongDAO.updateSauKhiTinhLuong(MaNV);
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        LoadDSLuong();
    }//GEN-LAST:event_TinhLuongButtonActionPerformed

    private void LuongJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LuongJTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LuongJTableMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void KhachHangLb16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhachHangLb16MouseClicked
        dispose();
        KhachHangFrame.main(currentUser);
    }//GEN-LAST:event_KhachHangLb16MouseClicked

    private void NhanVienLb16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhanVienLb16MouseClicked
        //        System.out.println(currentUser.toString());
        if (TrangChuDAO.KTLoaiNV(currentUser.getMaNV()) == 1) {
            dispose();
            NhanVienFrame.main(currentUser);
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập vào chức năng này", "Thông báo", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_NhanVienLb16MouseClicked

    private void ChamCongLb16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChamCongLb16MouseClicked
        if (TrangChuDAO.KTLoaiNV(currentUser.getMaNV()) == 1) {
            dispose();
            ChamCongFrame.main(currentUser);
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập vào chức năng này", "Thông báo", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_ChamCongLb16MouseClicked

    private void DangXuatLb16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuatLb16MouseClicked
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất không?", "Đăng xuất", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            dispose();
            DangNhapFrame.main(null);
        }
    }//GEN-LAST:event_DangXuatLb16MouseClicked

    private void TenNVTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenNVTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenNVTextFieldActionPerformed

  public void TraCuuLuong(){
        DefaultTableModel tblLuong_Model = (DefaultTableModel) this.LuongJTable.getModel();
        String option = String.valueOf(this.TimKiemTheoJCombobox.getSelectedItem());
        String input = this.NhapThongTinJTextField.getText();
        tblLuong_Model.setRowCount(0);
        ArrayList<LuongModel> DS_Luong = new ArrayList<LuongModel>();
        DS_Luong = LuongDAO.timNV(option, input);
        for (LuongModel luong:DS_Luong){
            tblLuong_Model.addRow(new Object[]{
                luong.getMaNV(),
                luong.getMaCC(),
                luong.getTenNV(),
                luong.getLoaiNV(),
                luong.getLuongCB(),
                luong.getSNDL(),
                luong.getSGLT()
            });
        }
        if (DS_Luong.size()<=0){
            JOptionPane.showMessageDialog(rootPane, "Thông tin không tồn tại. Vui lòng thử lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }
  
    public static void main(NhanVienModel args) {
         currentUser = args;
        currentUser.setMaNV(args.getMaNV());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LuongFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChamCongLb16;
    private javax.swing.JLabel DangXuatLb16;
    private javax.swing.JLabel HoaDonLb16;
    private javax.swing.JLabel HopDongLb16;
    private javax.swing.JLabel KhachHangLb16;
    private javax.swing.JLabel KhuyenMaiLb16;
    private javax.swing.JTable LuongJTable;
    private javax.swing.JTextField LuongTextField;
    private javax.swing.JPanel MenuPanel17;
    private javax.swing.JLabel NhanVienLb16;
    private javax.swing.JTextField NhapThongTinJTextField;
    private javax.swing.JTextField TenNVTextField;
    private javax.swing.JComboBox<String> TimKiemTheoJCombobox;
    private javax.swing.JButton TinhLuongButton;
    private javax.swing.JButton TraCuuButton;
    private javax.swing.JLabel TrangBiLb16;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel luongLb16;
    private javax.swing.JLabel phongLb16;
    // End of variables declaration//GEN-END:variables
}
