/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.LuongDAO;
import DAO.TrangChuDAO;
import Model.LuongModel;
import Model.NhanVienModel;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phuch
 */
public class LuongFrame extends javax.swing.JFrame {
    private static NhanVienModel currentUser;
    ArrayList<LuongModel> DS_Luong;
    private DefaultTableModel tblLuong_Model;
    private LuongDAO luongDAO;
    public LuongFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        DS_Luong = new ArrayList<>();
        DefaultTableModel DefaultTableModel;
        tblLuong_Model = (DefaultTableModel) this.LuongJTable.getModel();
        LoadDSLuong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        NhanVienButton = new javax.swing.JButton();
        KhachHangButton = new javax.swing.JButton();
        HopDongButton = new javax.swing.JButton();
        KhuyenMaiButton = new javax.swing.JButton();
        TrangBiButton = new javax.swing.JButton();
        HoaDonButton = new javax.swing.JButton();
        ChamCongButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TimKiemTheoJCombobox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        NhapThongTinJTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        LuongJTable = new javax.swing.JTable();
        TraCuuButton = new javax.swing.JButton();
        TinhLuongButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TenNVTextField = new javax.swing.JTextField();
        LuongTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuPanel.setBackground(new java.awt.Color(153, 153, 255));

        NhanVienButton.setText("Nhân Viên");
        NhanVienButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhanVienButtonMouseClicked(evt);
            }
        });

        KhachHangButton.setText("Khách Hàng");
        KhachHangButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KhachHangButtonMouseClicked(evt);
            }
        });
        KhachHangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhachHangButtonActionPerformed(evt);
            }
        });

        HopDongButton.setText("Hợp Đồng");
        HopDongButton.setPreferredSize(new java.awt.Dimension(75, 35));
        HopDongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HopDongButtonActionPerformed(evt);
            }
        });

        KhuyenMaiButton.setText("Khuyến Mãi");
        KhuyenMaiButton.setPreferredSize(new java.awt.Dimension(91, 35));
        KhuyenMaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhuyenMaiButtonActionPerformed(evt);
            }
        });

        TrangBiButton.setText("Trang Bị");
        TrangBiButton.setPreferredSize(new java.awt.Dimension(73, 35));
        TrangBiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrangBiButtonActionPerformed(evt);
            }
        });

        HoaDonButton.setText("Hóa Đơn");
        HoaDonButton.setPreferredSize(new java.awt.Dimension(78, 35));
        HoaDonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoaDonButtonActionPerformed(evt);
            }
        });

        ChamCongButton.setText("Chấm Công");
        ChamCongButton.setPreferredSize(new java.awt.Dimension(93, 35));
        ChamCongButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChamCongButtonMouseClicked(evt);
            }
        });
        ChamCongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChamCongButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChamCongButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(HoaDonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TrangBiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HopDongButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KhachHangButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(NhanVienButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KhuyenMaiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(KhachHangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NhanVienButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HopDongButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(KhuyenMaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TrangBiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(HoaDonButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ChamCongButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Lương");

        jLabel2.setText("Tìm kiếm theo ");

        TimKiemTheoJCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã NV", "Tên NV" }));
        TimKiemTheoJCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemTheoJComboboxActionPerformed(evt);
            }
        });

        jLabel3.setText("Nhập thông tin");

        NhapThongTinJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhapThongTinJTextFieldActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        LuongJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã CC", "Mã NV", "Tên NV", "Chức vụ", "Lương CB", "Số ngày đi làm ", "Số giờ làm thêm"
            }
        ));
        LuongJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LuongJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(LuongJTable);

        TraCuuButton.setText("Tra Cứu");
        TraCuuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraCuuButtonActionPerformed(evt);
            }
        });

        TinhLuongButton.setText("Tính Lương");
        TinhLuongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinhLuongButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Lương tháng này của nhân viên ");

        TenNVTextField.setEditable(false);

        LuongTextField.setEditable(false);

        jLabel5.setText("VNĐ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(TimKiemTheoJCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NhapThongTinJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(166, 166, 166)
                                .addComponent(TraCuuButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jLabel1))
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LuongTextField)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TinhLuongButton)
                                .addGap(23, 23, 23))
                            .addComponent(TenNVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimKiemTheoJCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NhapThongTinJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TraCuuButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TenNVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TinhLuongButton)
                    .addComponent(LuongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NhanVienButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhanVienButtonMouseClicked

        if (TrangChuDAO.KTLoaiNV(currentUser.getMaNV()) == 1) {
            dispose();
            NhanVienFrame.main(currentUser);
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập vào chức năng này", "Thông báo", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_NhanVienButtonMouseClicked

    private void KhachHangButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhachHangButtonMouseClicked
        if (TrangChuDAO.KTLoaiNV(currentUser.getMaNV()) == 1 || TrangChuDAO.KTLoaiNV(currentUser.getMaNV()) == 3) {
            dispose();
            KhachHangFrame.main(currentUser);
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập vào chức năng này", "Thông báo", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_KhachHangButtonMouseClicked

    private void KhachHangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KhachHangButtonActionPerformed
        /* dispose();
        KhachHangFrame.main(currentUser);*/
    }//GEN-LAST:event_KhachHangButtonActionPerformed

    private void HopDongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HopDongButtonActionPerformed
        /* dispose();
        HopDongFrame.main(currentUser);*/
    }//GEN-LAST:event_HopDongButtonActionPerformed

    private void KhuyenMaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KhuyenMaiButtonActionPerformed
        /* dispose();
        KhuyenMaiFrame.main(currentUser);*/
    }//GEN-LAST:event_KhuyenMaiButtonActionPerformed

    private void TrangBiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrangBiButtonActionPerformed
        /* dispose();
        TrangBiFrame.main(currentUser);*/
    }//GEN-LAST:event_TrangBiButtonActionPerformed

    private void HoaDonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoaDonButtonActionPerformed
        /*dispose();
        HoaDonFrame.main(currentUser);*/
    }//GEN-LAST:event_HoaDonButtonActionPerformed

    private void ChamCongButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChamCongButtonMouseClicked

    }//GEN-LAST:event_ChamCongButtonMouseClicked

    private void ChamCongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChamCongButtonActionPerformed

    }//GEN-LAST:event_ChamCongButtonActionPerformed

    private void NhapThongTinJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhapThongTinJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NhapThongTinJTextFieldActionPerformed

    private void TimKiemTheoJComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemTheoJComboboxActionPerformed
      
    }//GEN-LAST:event_TimKiemTheoJComboboxActionPerformed
    public void LoadDSLuong() {
        ArrayList<LuongModel> DS_Luong = new ArrayList<>();
        DS_Luong = LuongDAO.getDSLuong();
        DefaultTableModel tblHienThi = (DefaultTableModel) this.LuongJTable.getModel();
        tblHienThi.setRowCount(0);
        for (LuongModel luong : DS_Luong) {
            tblLuong_Model.addRow(new Object[]{
                luong.getMaCC(),
                luong.getMaNV(),
                luong.getTenNV(),
                luong.getLoaiNV(),
                luong.getLuongCB(),
                luong.getSNDL(),
                luong.getSGLT()
            });
        }
    }
    private void TraCuuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraCuuButtonActionPerformed
      String input = this.NhapThongTinJTextField.getText();
        if (input.equals(""))
            LoadDSLuong();
        else
            TraCuuLuong();
    }//GEN-LAST:event_TraCuuButtonActionPerformed

    private void TinhLuongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinhLuongButtonActionPerformed
            LuongDAO luongDAO = new LuongDAO();
        int chooseIndex = this.LuongJTable.getSelectedRow();
        DefaultTableModel tblLuong_Model = (DefaultTableModel) this.LuongJTable.getModel();
        try {
            if (chooseIndex == -1) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn nhân viên cần tính lương!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else if (this.LuongJTable.getRowCount() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Dữ liệu trống!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                int choice = JOptionPane.showOptionDialog(rootPane, "Bạn có muốn tính lương cho nhân viên?", "Tính lương", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
                if (choice == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(rootPane, "Lương của nhân viên đã được tính", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    String MaCC = (String) tblLuong_Model.getValueAt(chooseIndex, 0);
                    String MaNV = (String) tblLuong_Model.getValueAt(chooseIndex, 1);
                    String TenNV = (String) tblLuong_Model.getValueAt(chooseIndex, 2);
                    String LoaiNV = (String) tblLuong_Model.getValueAt(chooseIndex, 3);
                    Double LuongCB = (Double) tblLuong_Model.getValueAt(chooseIndex, 4);
                    int SoNgayDiLam = (int) tblLuong_Model.getValueAt(chooseIndex, 5);
                    int SoGioLamThem = (int) tblLuong_Model.getValueAt(chooseIndex, 6);
                    LuongModel luong = new LuongModel(MaNV, MaCC, TenNV, LoaiNV, LuongCB, SoNgayDiLam, SoGioLamThem);
                    this.TenNVTextField.setText(TenNV);
                    double luongNV = luongDAO.TinhLuong(luong);
                    NumberFormat numberFormat = NumberFormat.getCurrencyInstance();
                    String formattedNumber = numberFormat.format(luongNV);
                    this.LuongTextField.setText(formattedNumber);
                    LuongDAO.updateSauKhiTinhLuong(MaNV);
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        LoadDSLuong();
    }//GEN-LAST:event_TinhLuongButtonActionPerformed

    private void LuongJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LuongJTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LuongJTableMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

  public void TraCuuLuong(){
        DefaultTableModel tblLuong_Model = (DefaultTableModel) this.LuongJTable.getModel();
        String option = String.valueOf(this.TimKiemTheoJCombobox.getSelectedItem());
        String input = this.NhapThongTinJTextField.getText();
        tblLuong_Model.setRowCount(0);
        ArrayList<LuongModel> DS_Luong = new ArrayList<LuongModel>();
        DS_Luong = LuongDAO.timNV(option, input);
        for (LuongModel luong:DS_Luong){
            tblLuong_Model.addRow(new Object[]{
                luong.getMaNV(),
                luong.getMaCC(),
                luong.getTenNV(),
                luong.getLoaiNV(),
                luong.getLuongCB(),
                luong.getSNDL(),
                luong.getSGLT()
            });
        }
        if (DS_Luong.size()<=0){
            JOptionPane.showMessageDialog(rootPane, "Thông tin không tồn tại. Vui lòng thử lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }
  
    public static void main(NhanVienModel args) {
         currentUser = args;
        currentUser.setMaNV(args.getMaNV());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LuongFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChamCongButton;
    private javax.swing.JButton HoaDonButton;
    private javax.swing.JButton HopDongButton;
    private javax.swing.JButton KhachHangButton;
    private javax.swing.JButton KhuyenMaiButton;
    private javax.swing.JTable LuongJTable;
    private javax.swing.JTextField LuongTextField;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JButton NhanVienButton;
    private javax.swing.JTextField NhapThongTinJTextField;
    private javax.swing.JTextField TenNVTextField;
    private javax.swing.JComboBox<String> TimKiemTheoJCombobox;
    private javax.swing.JButton TinhLuongButton;
    private javax.swing.JButton TraCuuButton;
    private javax.swing.JButton TrangBiButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
