ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER database_doan_NPNT IDENTIFIED BY password;
GRANT CONNECT, RESOURCE, DBA TO database_doan_NPNT;

ALTER SESSION SET CURRENT_SCHEMA = database_doan_NPNT;

-- Tạo bảng
-- Tạo bảng khách hàng
CREATE TABLE KHACHHANG (
  MaKH NUMBER PRIMARY KEY,
  TenKH NVARCHAR2(50),
  CCCD CHAR(12),
  NgaySinh DATE,
  GioiTinh NVARCHAR2(3),  -- 'Nam', 'Nữ'
  DiaChi NVARCHAR2(100),
  SDT CHAR(10),
  SoHopDong INT
);

DROP TABLE NHANVIEN 
-- Tạo bảng nhân viên
CREATE TABLE NHANVIEN (
  MaNV NUMBER PRIMARY KEY,
  TenNV NVARCHAR2(50),
  CCCD CHAR(12),
  NgaySinh DATE,
  GioiTinh NVARCHAR2(3),  -- 'Nam', 'Nữ'
  DiaChi NVARCHAR2(100),
  SDT CHAR(10),
  LoaiNV NVARCHAR2(20),    -- 'Tạp Vụ', 'Lễ Tân', 'Quản lý'
  TaiKhoan VARCHAR2(20),
  MatKhau VARCHAR2(20),
  LuongCB NUMBER
);

-- Tạo bảng hợp đồng đặt phòng tạm
CREATE TABLE HOPDONG(
  MaHopDong NUMBER PRIMARY KEY,
  MaKH NUMBER,
  NgayLapHopDong TIMESTAMP,
  TGNhanPhong TIMESTAMP,
  TGTraPhong TIMESTAMP,
  TinhTrangHD NVARCHAR2(20),  -- 'Đã xác nhận', 'Chưa xác nhận'
  SoNguoiLon NUMBER,
  SoTreEm NUMBER,
  TriGiaHD NUMBER  -- Tiền cọc của hợp đồng
);

-- Tạo bảng phòng
CREATE TABLE PHONG  (
  MaPhong NUMBER PRIMARY KEY,
  LoaiPhong VARCHAR2(20),
  KieuPhong VARCHAR2(20),
  Gia NUMBER
);

-- Tạo bảng chi tiết đặt phòng 
CREATE TABLE CHITIETDATPHONG (
  MaHopDong NUMBER NOT NULL,
  MaPhong NUMBER NOT NULL,
  CONSTRAINT PK_CTDP PRIMARY KEY (MaHopDong, MaPhong)
);

-- Tạo bảng trang bị
CREATE TABLE TRANGBI (
  MaTB NUMBER PRIMARY KEY,
  TenTB NVARCHAR2(50),
  GiaTB NUMBER,
  SoLuong INT
);

-- Tạo bảng khuyến mãi
CREATE TABLE KHUYENMAI (
  MaKM NUMBER PRIMARY KEY,
  TenKM NVARCHAR2(50),
  MoTaKM NVARCHAR2(200),
  NgayBatDau DATE,
  NgayKetThuc DATE,
  PhanTramKM NUMERIC(3,2)
);

-- Tạo bảng hóa đơn 
CREATE TABLE HOADON (
  MaHD NUMBER PRIMARY KEY,
  MaKM NUMBER,   -- với mỗi hóa đơn chỉ áp dụng được 1 loại khuyến mãi
  MaHopDong NUMBER,  
  NgayLapHD DATE,
  TongTien NUMBER
);

-- Tạo bảng hỏng trang bị 
CREATE TABLE HONGTRANGBI (
  MaTB NUMBER,
  MaHD NUMBER,
  SoLuongHong INT,
  CONSTRAINT PK_HONGTRANGBI PRIMARY KEY (MaTB, MaHD)
);

-- Tạo bảng tạo hóa đơn
CREATE TABLE TAOHOADON (
  MaHD NUMBER,
  MaNV NUMBER,
  CONSTRAINT PK_TAOHOADON PRIMARY KEY(MaHD, MaNV)
);

-- Tạo bảng chấm công
CREATE TABLE CHAMCONG (
  MaCC NUMBER PRIMARY KEY,
  MaNV NUMBER,
  SoGioLamThem INT,
  SoNgayDiLam INT
);

-- Tạo UINIQUE cho các thuộc tính là duy nhất trong oracle
-- Bảng Khách hàng
ALTER TABLE KHACHHANG
ADD CONSTRAINT KHACHHANG_UNIQUE_CCCD UNIQUE(CCCD);

ALTER TABLE KHACHHANG
ADD CONSTRAINT KHACHHANG_UNIQUE_SDT UNIQUE(SDT);

-- Bảng Nhân viên
ALTER TABLE NHANVIEN
ADD CONSTRAINT NHANVIEN_UNIQUE_CCCD UNIQUE(CCCD);

ALTER TABLE NHANVIEN
ADD CONSTRAINT NHANVIEN_UNIQUE_SDT UNIQUE(SDT);


-- Tạo sequence cho database
CREATE SEQUENCE KhachHang_Seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE NhanVien_Seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE HopDong_Seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE Phong_Seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TrangBi_Seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE KhuyenMai_Seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE HoaDon_Seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ChamCong_Seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Xóa sequence
DROP SEQUENCE KhachHang_Seq;
DROP SEQUENCE NhanVien_Seq;
DROP SEQUENCE HopDong_Seq;
DROP SEQUENCE Phong_Seq;
DROP SEQUENCE TrangBi_Seq;
DROP SEQUENCE KhuyenMai_Seq;
DROP SEQUENCE HoaDon_Seq;
DROP SEQUENCE ChamCong_Seq;


-- Tạo khóa ngoại 
ALTER TABLE HOPDONG
ADD CONSTRAINT FK_HOPDONG_KHACHHANG FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH); 

ALTER TABLE CHITIETDATPHONG
ADD CONSTRAINT FK_CTHDong_HOPDONG FOREIGN KEY (MaHopDong) REFERENCES HOPDONG(MaHopDong);

ALTER TABLE CHITIETDATPHONG
ADD CONSTRAINT FK_CTHDong_PHONG FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong);

ALTER TABLE HONGTRANGBI
ADD CONSTRAINT FK_HONGTB_TRANGBI FOREIGN KEY (MaTB) REFERENCES TRANGBI(MaTB);

ALTER TABLE HONGTRANGBI
ADD CONSTRAINT FK_HONGTB_HOADON FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD);

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_KHUYENMAI FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM);

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_HOPDONG FOREIGN KEY (MaHopDong) REFERENCES HOPDONG(MaHopDong);

ALTER TABLE TAOHOADON
ADD CONSTRAINT FK_TAOHD_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE TAOHOADON
ADD CONSTRAINT FK_TAOHD_HOADON FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD);

ALTER TABLE CHAMCONG
ADD CONSTRAINT FK_CHAMCONG_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);


-- INSERT DỮ LIỆU
-- insert bảng khách hàng
INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
(KhachHang_Seq.NEXTVAL, 'Nguyễn Văn An', '012345678901', TO_DATE('01-01-1999', 'DD-MM-YYYY'), 'Nam', '123 Lê Lợi, Hà Nội', '0912345678', 2);

INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
(KhachHang_Seq.NEXTVAL, 'Trần Thị Bình', '012345678902', TO_DATE('15-02-1995', 'DD-MM-YYYY'), 'Nữ', '456 Trần Hưng Đạo, Đà Nẵng', '0912345679', 1);

INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
(KhachHang_Seq.NEXTVAL, 'Lê Mạnh Cường', '012345678903', TO_DATE('20-03-1998', 'DD-MM-YYYY'), 'Nam', '789 Nguyễn Trãi, Hồ Chí Minh', '0912345680', 1);

INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
(KhachHang_Seq.NEXTVAL, 'Phạm Thị Diệu', '012345678904', TO_DATE('25-04-1995', 'DD-MM-YYYY'), 'Nữ', '321 Phan Chu Trinh, Cần Thơ', '0912345681', 1);

INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
(KhachHang_Seq.NEXTVAL, 'Hoàng Văn Huy', '012345678905', TO_DATE('30-05-2000', 'DD-MM-YYYY'), 'Nam', '654 Hai Bà Trưng, Huế', '0912345682', 2);

INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
(KhachHang_Seq.NEXTVAL, 'Vũ Thị Linh', '012345678906', TO_DATE('10-06-1997', 'DD-MM-YYYY'), 'Nữ', '987 Lê Thánh Tông, Hạ Long', '0912345683', 1);

INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
(KhachHang_Seq.NEXTVAL, 'Đặng Văn Lâm', '012345678907', TO_DATE('15-07-1993', 'DD-MM-YYYY'), 'Nam', '123 Võ Nguyên Giáp, Nha Trang', '0912345684', 1);

INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
(KhachHang_Seq.NEXTVAL, 'Bùi Thị Hiền', '012345678908', TO_DATE('20-08-1991', 'DD-MM-YYYY'), 'Nữ', '456 Lê Hồng Phong, Đà Lạt', '0912345685', 1);

INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
(KhachHang_Seq.NEXTVAL, 'Ngô Trần Văn Trung', '012345678909', TO_DATE('25-09-2002', 'DD-MM-YYYY'), 'Nam', '789 Trần Phú, Hải Phòng', '0912345686', 3);

INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
(KhachHang_Seq.NEXTVAL, 'Đỗ Nguyễn Ngọc Nữ', '012345678910', TO_DATE('30-10-1989', 'DD-MM-YYYY'), 'Nữ', '321 Nguyễn Huệ, Vũng Tàu', '0912345687', 2);

COMMIT;
SELECT * FROM KHACHHANG;
UPDATE KHACHHANG SET SOHOPDONG = 0 WHERE MAKH IN (1,2,3,4,5,6,7,8,9,10);
DELETE KHACHHANG WHERE MAKH = 2;





SELECT * FROM NHANVIEN n;
DELETE NHANVIEN WHERE MANV = 12;
UPDATE NHANVIEN SET LOAINV = 'Lễ tân' WHERE MANV = 3;
DELETE FROM NHANVIEN WHERE MaNV IN (1,2,3,4,5,6,7,8,9,10,11,12);
COMMIT;
--insert dữ liệu nhân viên
INSERT INTO NHANVIEN (MANV, TENNV, CCCD, GIOITINH, NGAYSINH, DIACHI, LOAINV, TAIKHOAN, MATKHAU, SDT, LUONGCB) 
	VALUES (NhanVien_Seq.NEXTVAL, 'Nguyễn Minh Thái', '098765432101', 'Nam', TO_DATE('1-1-1985', 'DD-MM-YYYY'), '123 Đường ABC, Hà Nội', 'Quản lý', 'quanly1', 'qlpass', '0901256567', 1000000);

INSERT INTO DATABASE_DOAN_NPNT.NHANVIEN (MANV, TENNV, CCCD, GIOITINH, NGAYSINH, DIACHI, LOAINV, TAIKHOAN, MATKHAU, SDT, LUONGCB) 
	VALUES (NhanVien_Seq.NEXTVAL, 'Hoàng Hào Quang', '456789012345', 'Nam', TO_DATE('10-11-1992', 'DD-MM-YYYY'), '202 Đường JKL, Cần Thơ', 'Lễ tân', 'letan2', 'ltpass', '0943378901', 700000);

INSERT INTO DATABASE_DOAN_NPNT.NHANVIEN (MANV, TENNV, CCCD, GIOITINH, NGAYSINH, DIACHI, LOAINV, TAIKHOAN, MATKHAU, SDT, LUONGCB) 
	VALUES (NhanVien_Seq.NEXTVAL, 'Ngô Nguyễn Tố Như', '567890123456', 'Nữ', TO_DATE('5-2-2000', 'DD-MM-YYYY'), '303 Đường MNO, Huế', 'Lễ tân', 'letan3', 'ltpass', '0956788112', 650000);

INSERT INTO DATABASE_DOAN_NPNT.NHANVIEN (MANV, TENNV, CCCD, GIOITINH, NGAYSINH, DIACHI, LOAINV, TAIKHOAN, MATKHAU, SDT, LUONGCB) 
	VALUES (NhanVien_Seq.NEXTVAL, 'Vũ Thị Xuân', '098765432102', 'Nữ', TO_DATE('15-5-1990', 'DD-MM-YYYY'), '456 Đường XYZ, TP. Hồ Chí Minh', 'Tạp Vụ', NULL, NULL, '0912444568', 300000);

INSERT INTO DATABASE_DOAN_NPNT.NHANVIEN (MANV, TENNV, CCCD, GIOITINH, NGAYSINH, DIACHI, LOAINV, TAIKHOAN, MATKHAU, SDT, LUONGCB) 
	VALUES (NhanVien_Seq.NEXTVAL, 'Lê Văn Hùng', '234567890123', 'Nam', TO_DATE('22-3-1988', 'DD-MM-YYYY'), '789 Đường DEF, Đà Nẵng', 'Tạp Vụ', NULL, NULL, '0923456711', 350000);

INSERT INTO DATABASE_DOAN_NPNT.NHANVIEN (MANV, TENNV, CCCD, GIOITINH, NGAYSINH, DIACHI, LOAINV, TAIKHOAN, MATKHAU, SDT, LUONGCB) 
	VALUES (NhanVien_Seq.NEXTVAL, 'Phạm Ngọc Nhung', '345678901234', 'Nữ', TO_DATE('30-7-1999', 'DD-MM-YYYY'), '101 Đường GHI, Hải Phòng', 'Lễ tân', 'letan6', 'ltpass', '0930967890', 500000);

INSERT INTO DATABASE_DOAN_NPNT.NHANVIEN (MANV, TENNV, CCCD, GIOITINH, NGAYSINH, DIACHI, LOAINV, TAIKHOAN, MATKHAU, SDT, LUONGCB) 
  VALUES (NhanVien_Seq.NEXTVAL, 'Phạm Văn Thắng', '345678901234', 'Nam', TO_DATE('22-3-1988', 'DD-MM-YYYY'), '789 Đường DEF, Đà Nẵng',  'Tạp Vụ',  NULL,  NULL,'0923456711', 350000);




SELECT * FROM HOPDONGTHUEPHONG;
--Insert dữ liệu hợp đồng thuê phòng
-- Hợp đồng cho Nguyễn Văn An (2 hợp đồng)
INSERT INTO HOPDONG (MaHopDong, MaKH, NgayLapHopDong, TGNhanPhong, TGTraPhong, TinhTrangHD, SoNguoiLon, SoTreEm, TriGiaHD) VALUES
(HopDong_Seq.NEXTVAL, 1, TO_DATE('2024-01-10', 'YYYY-MM-DD'), TO_DATE('2024-01-12', 'YYYY-MM-DD'), TO_DATE('2024-01-15', 'YYYY-MM-DD'), 'Đã xác nhận', 2, 1, 1000000);

INSERT INTO HOPDONG (MaHopDong, MaKH, NgayLapHopDong, TGNhanPhong, TGTraPhong, TinhTrangHD, SoNguoiLon, SoTreEm, TriGiaHD) VALUES
(HopDong_Seq.NEXTVAL, 1, TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-03-17', 'YYYY-MM-DD'), TO_DATE('2024-03-20', 'YYYY-MM-DD'), 'Đã xác nhận', 2, 2, 2000000);

-- Hợp đồng cho Trần Thị Bình (1 hợp đồng)
INSERT INTO HOPDONG (MaHopDong, MaKH, NgayLapHopDong, TGNhanPhong, TGTraPhong, TinhTrangHD, SoNguoiLon, SoTreEm, TriGiaHD) VALUES
(HopDong_Seq.NEXTVAL, 2, TO_DATE('2024-02-01', 'YYYY-MM-DD'), TO_DATE('2024-02-03', 'YYYY-MM-DD'), TO_DATE('2024-02-06', 'YYYY-MM-DD'), 'Đã xác nhận', 1, 0, 1500000);

-- Hợp đồng cho Lê Mạnh Cường (1 hợp đồng)
INSERT INTO HOPDONG (MaHopDong, MaKH, NgayLapHopDong, TGNhanPhong, TGTraPhong, TinhTrangHD, SoNguoiLon, SoTreEm, TriGiaHD) VALUES
(HopDong_Seq.NEXTVAL, 3, TO_DATE('2024-04-05', 'YYYY-MM-DD'), TO_DATE('2024-04-07', 'YYYY-MM-DD'), TO_DATE('2024-04-10', 'YYYY-MM-DD'), 'Đã xác nhận', 2, 1, 1800000);

-- Hợp đồng cho Phạm Thị Diệu (1 hợp đồng)
INSERT INTO HOPDONG (MaHopDong, MaKH, NgayLapHopDong, TGNhanPhong, TGTraPhong, TinhTrangHD, SoNguoiLon, SoTreEm, TriGiaHD) VALUES
(HopDong_Seq.NEXTVAL, 4, TO_DATE('2024-05-15', 'YYYY-MM-DD'), TO_DATE('2024-05-17', 'YYYY-MM-DD'), TO_DATE('2024-05-20', 'YYYY-MM-DD'), 'Đã xác nhận', 1, 2, 1600000);

-- Hợp đồng cho Hoàng Văn Huy (2 hợp đồng)
INSERT INTO HOPDONG (MaHopDong, MaKH, NgayLapHopDong, TGNhanPhong, TGTraPhong, TinhTrangHD, SoNguoiLon, SoTreEm, TriGiaHD) VALUES
(HopDong_Seq.NEXTVAL, 5, TO_DATE('2024-06-01', 'YYYY-MM-DD'), TO_DATE('2024-06-03', 'YYYY-MM-DD'), TO_DATE('2024-06-06', 'YYYY-MM-DD'), 'Đã xác nhận', 3, 0, 2200000);

INSERT INTO HOPDONG (MaHopDong, MaKH, NgayLapHopDong, TGNhanPhong, TGTraPhong, TinhTrangHD, SoNguoiLon, SoTreEm, TriGiaHD) VALUES
(HopDong_Seq.NEXTVAL, 5, TO_DATE('2024-07-10', 'YYYY-MM-DD'), TO_DATE('2024-07-12', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'), 'Đã xác nhận', 2, 2, 2300000);

-- Hợp đồng cho Vũ Thị Linh (1 hợp đồng)
INSERT INTO HOPDONG (MaHopDong, MaKH, NgayLapHopDong, TGNhanPhong, TGTraPhong, TinhTrangHD, SoNguoiLon, SoTreEm, TriGiaHD) VALUES
(HopDong_Seq.NEXTVAL, 6, TO_DATE('2024-08-20', 'YYYY-MM-DD'), TO_DATE('2024-08-22', 'YYYY-MM-DD'), TO_DATE('2024-08-25', 'YYYY-MM-DD'), 'Đã xác nhận', 1, 0, 1300000);

-- Hợp đồng cho Đặng Văn Lâm (1 hợp đồng)
INSERT INTO HOPDONG (MaHopDong, MaKH, NgayLapHopDong, TGNhanPhong, TGTraPhong, TinhTrangHD, SoNguoiLon, SoTreEm, TriGiaHD) VALUES
(HopDong_Seq.NEXTVAL, 7, TO_DATE('2024-09-05', 'YYYY-MM-DD'), TO_DATE('2024-09-07', 'YYYY-MM-DD'), TO_DATE('2024-09-10', 'YYYY-MM-DD'), 'Đã xác nhận', 3, 1, 2500000);

-- Hợp đồng cho Bùi Thị Hiền (1 hợp đồng)
INSERT INTO HOPDONG (MaHopDong, MaKH, NgayLapHopDong, TGNhanPhong, TGTraPhong, TinhTrangHD, SoNguoiLon, SoTreEm, TriGiaHD) VALUES
(HopDong_Seq.NEXTVAL, 8, TO_DATE('2024-10-12', 'YYYY-MM-DD'), TO_DATE('2024-10-14', 'YYYY-MM-DD'), TO_DATE('2024-10-17', 'YYYY-MM-DD'), 'Đã xác nhận', 2, 2, 2400000);

-- Hợp đồng cho Ngô Trần Văn Trung (3 hợp đồng)
INSERT INTO HOPDONG (MaHopDong, MaKH, NgayLapHopDong, TGNhanPhong, TGTraPhong, TinhTrangHD, SoNguoiLon, SoTreEm, TriGiaHD) VALUES
(HopDong_Seq.NEXTVAL, 9, TO_DATE('2024-11-01', 'YYYY-MM-DD'), TO_DATE('2024-11-03', 'YYYY-MM-DD'), TO_DATE('2024-11-06', 'YYYY-MM-DD'), 'Đã xác nhận', 2, 0, 2100000);

INSERT INTO HOPDONG (MaHopDong, MaKH, NgayLapHopDong, TGNhanPhong, TGTraPhong, TinhTrangHD, SoNguoiLon, SoTreEm, TriGiaHD) VALUES
(HopDong_Seq.NEXTVAL, 9, TO_DATE('2024-12-10', 'YYYY-MM-DD'), TO_DATE('2024-12-12', 'YYYY-MM-DD'), TO_DATE('2024-12-15', 'YYYY-MM-DD'), 'Đã xác nhận', 3, 1, 2200000);

INSERT INTO HOPDONG (MaHopDong, MaKH, NgayLapHopDong, TGNhanPhong, TGTraPhong, TinhTrangHD, SoNguoiLon, SoTreEm, TriGiaHD) VALUES
(HopDong_Seq.NEXTVAL, 9, TO_DATE('2024-12-20', 'YYYY-MM-DD'), TO_DATE('2024-12-22', 'YYYY-MM-DD'), TO_DATE('2024-12-25', 'YYYY-MM-DD'), 'Đã xác nhận', 2, 2, 2300000);

-- Hợp đồng cho Đỗ Nguyễn Ngọc Nữ (2 hợp đồng)
INSERT INTO HOPDONG (MaHopDong, MaKH, NgayLapHopDong, TGNhanPhong, TGTraPhong, TinhTrangHD, SoNguoiLon, SoTreEm, TriGiaHD) VALUES
(HopDong_Seq.NEXTVAL, 10, TO_DATE('2023-02-17', 'YYYY-MM-DD'), TO_DATE('2024-03-17', 'YYYY-MM-DD'), TO_DATE('2024-03-20', 'YYYY-MM-DD'), 'Đã xác nhận', 1, 1, 1900000);

INSERT INTO HOPDONG (MaHopDong, MaKH, NgayLapHopDong, TGNhanPhong, TGTraPhong, TinhTrangHD, SoNguoiLon, SoTreEm, TriGiaHD) VALUES
(HopDong_Seq.NEXTVAL, 10, TO_DATE('2024-01-15', 'YYYY-MM-DD'), TO_DATE('2024-01-17', 'YYYY-MM-DD'), TO_DATE('2024-01-20', 'YYYY-MM-DD'), 'Đã xác nhận', 3, 0, 1900000);

INSERT INTO HOPDONG(MaHopDong, MaKH, NgayLapHopDong, TGNhanPhong, TGTraPhong, TinhTrangHD, SoNguoiLon, SoTreEm, TriGiaHD) VALUES
(HopDong_Seq.NEXTVAL, 10, TO_DATE('2024-06-15', 'YYYY-MM-DD'), TO_DATE('2024-06-17', 'YYYY-MM-DD'), TO_DATE('2024-06-20', 'YYYY-MM-DD'), 'Đã xác nhận', 2, 0, 1900000);


INSERT INTO HOPDONG (  MaHopDong, MaKH, NgayLapHopDong, TGNhanPhong, TGTraPhong, TinhTrangHD, SoNguoiLon, SoTreEm, TriGiaHD) 
VALUES (99, 101, SYSTIMESTAMP, TO_TIMESTAMP('2023-06-01 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-06-10 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Đã xác nhận', 2, 1, 5000000);


COMMIT;
SELECT * FROM HOPDONG WHERE H.TINHTRANGHD = 'Chưa xác nhận' ORDER BY MaHopDong DESC;


-- Trigger
-- Chạy mã để tạo trigger
CREATE OR REPLACE TRIGGER trg_update_sohopdong
AFTER INSERT ON HOPDONG
FOR EACH ROW
BEGIN
  -- Cập nhật số hợp đồng của khách hàng tương ứng
  UPDATE KHACHHANG
  SET SoHopDong = SoHopDong + 1
  WHERE MaKH = :NEW.MaKH;
END;
/
