ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER database_doan_NPNT IDENTIFIED BY password;
GRANT CONNECT, RESOURCE, DBA TO database_doan_NPNT;

ALTER SESSION SET CURRENT_SCHEMA = database_doan_NPNT;

-- Tạo bảng
-- Tạo bảng khách hàng
CREATE TABLE KHACHHANG (
  MaKH VARCHAR2(6) PRIMARY KEY,
  TenKH NVARCHAR2(50),
  CCCD CHAR(12),
  NgaySinh DATE,
  GioiTinh NVARCHAR2(3),  -- 'Nam', 'Nữ'
  DiaChi NVARCHAR2(100),
  SDT CHAR(10),
  SoHopDong INT
);

-- Tạo bảng nhân viên
CREATE TABLE NHANVIEN (
  MaNV VARCHAR2(6) PRIMARY KEY,
  TenNV NVARCHAR2(50),
  CCCD CHAR(12),
  GioiTinh NVARCHAR2(3),  -- 'Nam', 'Nữ'
  NgaySinh DATE,
  DiaChi NVARCHAR2(100),
  SDT CHAR(10),
  LoaiNV NVARCHAR2(20),    -- 'Tạp Vụ', 'Lễ Tân', 'Quản lý'
  TaiKhoan VARCHAR2(20),
  MatKhau VARCHAR(20),
  LuongCB NUMBER
);

-- Tạo bảng hợp đồng đặt phòng tạm
CREATE TABLE HOPDONGTHUEPHONG (
  MaHopDong VARCHAR2(6) PRIMARY KEY,
  MaKH VARCHAR2(6),
  NgayLapHopDong TIMESTAMP,
  TGNhanPhong TIMESTAMP,
  TGTraPhong TIMESTAMP,
  TinhTrangHD NVARCHAR2(20),  -- 'Đã xác nhận', 'Chưa xác nhận'
  SoNguoiLon NUMBER,
  SoTreEm NUMBER,
  TriGiaHD NUMBER  -- Tiền cọc của hợp đồng
);

-- Tạo bảng hình thức thuê phòng 
CREATE TABLE HINHTHUCTHUE (
  MaHT VARCHAR2(6) PRIMARY KEY,
  TenHT NVARCHAR2(10) -- 'Giờ', 'Ngày'
);

-- Tạo bảng phòng
CREATE TABLE PHONG  (
  MaPhong VARCHAR2(6) PRIMARY KEY,
	LoaiPhong VARCHAR2(20),
	KieuPhong VARCHAR2(20)
);

-- Tạo bảng chi tiết đặt phòng 
CREATE TABLE CHITIETTHUEPHONG (
	MaHopDong VARCHAR2(6) NOT NULL,
	MaPhong VARCHAR2(6) NOT NULL,
	MaHT VARCHAR2(6) NOT NULL,
	Gia NUMBER,
	CONSTRAINT PK_CTDP PRIMARY KEY (MaHopDong, MaPhong, MaHT)
);

-- Tạo bảng trang bị
CREATE TABLE TRANGBI (
	MaTB VARCHAR2(6) PRIMARY KEY,
	TenTB NVARCHAR2(50),
  GiaTB NUMBER,
  SoLuong INT
);

-- Tạo bảng khuyến mãi
CREATE TABLE KHUYENMAI (
	MaKM VARCHAR2(6) PRIMARY KEY,
	TenKM NVARCHAR2(50),
	MoTaKM NVARCHAR2(200),
	NgayBatDau DATE,
	NgayKetThuc DATE,
  PhanTramKM NUMERIC(3,2)
);

-- Tạo bảng hóa đơn 
CREATE TABLE HOADON (
	MaHD VARCHAR2(6) PRIMARY KEY,
	MaKM VARCHAR2(6),   -- với mỗi hóa đơn chỉ áp dụng được 1 loại khuyến mãi
	MaHopDong VARCHAR2(6),  
	NgayLapHD DATE,
	TongTien NUMBER
);

-- Tạo bảng hỏng trang bị 
CREATE TABLE HONGTRANGBI (
  MaTB VARCHAR2(6),
  MaHD VARCHAR2(6),
  SoLuongHong INT,
  CONSTRAINT PK_HONGTRANGBI PRIMARY KEY (MaTB, MaHD)
);

-- Tạo bảng tạo hóa đơn
CREATE TABLE TAOHOADON (
	MaHD VARCHAR2(6),
	MaNV VARCHAR2(6),
	CONSTRAINT PK_TAOHOADON PRIMARY KEY(MaHD, MaNV)
);

-- Tạo bảng chấm công
CREATE TABLE CHAMCONG (
  MaCC VARCHAR(6) PRIMARY KEY,
  MaNV VARCHAR(6),
  SoGioLamThem INT,
  SoNgayDiLam INT
);

-- Tạo khóa ngoại 
ALTER TABLE HOPDONGTHUEPHONG
ADD CONSTRAINT FK_HOPDONG_KHACHHANG FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH); 

ALTER TABLE CHITIETTHUEPHONG
ADD CONSTRAINT FK_CTHDong_HINHTHUC FOREIGN KEY (MaHT) REFERENCES HINHTHUCTHUE(MaHT);

ALTER TABLE CHITIETTHUEPHONG
ADD CONSTRAINT FK_CTHDong_HOPDONG FOREIGN KEY (MaHopDong) REFERENCES HOPDONGTHUEPHONG(MaHopDong);

ALTER TABLE CHITIETTHUEPHONG
ADD CONSTRAINT FK_CTHDong_PHONG FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong);

ALTER TABLE HONGTRANGBI
ADD CONSTRAINT FK_HONGTB_TRANGBI FOREIGN KEY (MaTB) REFERENCES TRANGBI(MaTB);

ALTER TABLE HONGTRANGBI
ADD CONSTRAINT FK_HONGTB_HOADON FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD);

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_KHUYENMAI FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM);

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_HOPDONG FOREIGN KEY (MaHopDong) REFERENCES HOPDONGTHUEPHONG(MaHopDong);

ALTER TABLE TAOHOADON
ADD CONSTRAINT FK_TAOHD_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE TAOHOADON
ADD CONSTRAINT FK_TAOHD_HOADON FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD);

ALTER TABLE CHAMCONG
ADD CONSTRAINT FK_CHAMCONG_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);


-- INSERT DỮ LIỆU
-- insert bảng khách hàng
INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
('KH0001', 'Nguyễn Văn An', '012345678901', TO_DATE('1999-01-01', 'YYYY-MM-DD'), 'Nam', '123 Lê Lợi, Hà Nội', '0912345678', 2);
INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
('KH0002', 'Trần Thị Bình', '012345678902', TO_DATE('1995-02-15', 'YYYY-MM-DD'), 'Nữ', '456 Trần Hưng Đạo, Đà Nẵng', '0912345679', 1);
INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
('KH0003', 'Lê Mạnh Cường', '012345678903', TO_DATE('1998-03-20', 'YYYY-MM-DD'), 'Nam', '789 Nguyễn Trãi, Hồ Chí Minh', '0912345680', 1);
INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
('KH0004', 'Phạm Thị Diệu', '012345678904', TO_DATE('1995-04-25', 'YYYY-MM-DD'), 'Nữ', '321 Phan Chu Trinh, Cần Thơ', '0912345681', 1);
INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
('KH0005', 'Hoàng Văn Huy', '012345678905', TO_DATE('2000-05-30', 'YYYY-MM-DD'), 'Nam', '654 Hai Bà Trưng, Huế', '0912345682', 2);
INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
('KH0006', 'Vũ Thị Linh', '012345678906', TO_DATE('1997-06-10', 'YYYY-MM-DD'), 'Nữ', '987 Lê Thánh Tông, Hạ Long', '0912345683', 1);
INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
('KH0007', 'Đặng Văn Lâm', '012345678907', TO_DATE('1993-07-15', 'YYYY-MM-DD'), 'Nam', '123 Võ Nguyên Giáp, Nha Trang', '0912345684', 1);
INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
('KH0008', 'Bùi Thị Hiền', '012345678908', TO_DATE('1991-08-20', 'YYYY-MM-DD'), 'Nữ', '456 Lê Hồng Phong, Đà Lạt', '0912345685', 1);
INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
('KH0009', 'Ngô Trần Văn Trung', '012345678909', TO_DATE('2002-09-25', 'YYYY-MM-DD'), 'Nam', '789 Trần Phú, Hải Phòng', '0912345686', 3);
INSERT INTO KHACHHANG (MaKH, TenKH, CCCD, NgaySinh, GioiTinh, DiaChi, SDT, SoHopDong) VALUES
('KH0010', 'Đỗ Nguyễn Ngọc Nữ', '012345678910', TO_DATE('1989-10-30', 'YYYY-MM-DD'), 'Nữ', '321 Nguyễn Huệ, Vũng Tàu', '0912345687', 2);
COMMIT;
SELECT * FROM KHACHHANG;

------------------------------- NHÂN VIÊN ------------------------------------
-- Thêm nhà nhân viên 
CREATE OR REPLACE PROCEDURE insert_NHANVIEN(
    p_MaNV NHANVIEN.MANV%TYPE,
    p_HoTen NHANVIEN.TENNV%TYPE,
    p_CCCD NHANVIEN.CCCD%TYPE,
    p_GioiTinh NHANVIEN.GIOITINH%TYPE,
    p_NgaySinh NHANVIEN.NGAYSINH%TYPE,
    p_DiaChi NHANVIEN.DIACHI%TYPE,
    p_SDT NHANVIEN.SDT%TYPE,
    p_LoaiNV NHANVIEN.LOAINV%TYPE,
    p_TaiKhoan NHANVIEN.TAIKHOAN%TYPE,
    p_MatKhau NHANVIEN.MATKHAU%TYPE,
    p_LuongCB NHANVIEN.LUONGCB%TYPE
)
IS
BEGIN
    INSERT INTO NHANVIEN (MANV, TENNV,CCCD, GIOITINH, NGAYSINH, DIACHI, SDT, LOAINV, TAIKHOAN, MATKHAU, LUONGCB) )
    VALUES (p_MaNV, p_HoTen,p_CCCD, p_GioiTinh, p_NgaySinh, p_DiaChi, p_SDT, p_LoaiNV, p_TaiKhoan, p_MatKhau, p_LuongCB);
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
END;
/




